# Generated by Django 2.2.28 on 2025-02-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250212_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-title']},
        ),
    ]
